### PR TITLE
#244 kumo_particle_helper plus docs

### PR DESCRIPTION
**Pull request by markfink**
## Checklist before opening PR 
- [x] Issue / PR description provided
- [ ] This feature has test coverage
- [x] This feature has documentation (docs)
- [x] The changelog has been updated (docs/CHANGELOG.md)

## Contributor License Agreement

gcdt is an open-source project that is licensed very permissively (see LICENSE). This means that software, and other contributions to the project are released to the public to be freely used, modified, remixed, and even sold without anyone’s permission. In order to protect this freedom, contributors must agree to waive their rights to their contributions BEFORE contributing them.

By submitting a pull request to gcdt you agree to this Contributor License Agreement, you are waiving your rights to the intellectual property that you contribute to the gcdt project. You agree to put your contribution under MIT license.

### CODE REVIEW

**Comment by jbrandstetter** [comment]
Hi,
I love this feature :-) Still a question: As I understood we didn't want tight coupling of particles to gcdt/kumo. My impression was that we keep kumo as a more or less agnostic deployment tool for arbitrary cf templates and that within our cloudformation.py we would use/import the particles module(s) to actually build the template?

**Comment by markfink** [comment]
exactly! We just provide the kumo_particle_helper alongside servicediscovery, iam and others cloudformation helpers that can be optionaly used within `cloudformation.py` . There is no tight coupling - kumo-particles use is totally optional. For example you can bring your own building block mechanism and deploy with kumo.

**Comment by jbrandstetter** [comment]
Perfect!

**Comment by markfink** [comment]
docs here: http://gcdt.readthedocs.io/en/latest/22_kumo_particles.html

**Pull request merged**
