### PR TITLE
Add support for ENV variables

### PR DESCRIPTION
**Pull request by Tonkonozhenko**
## Description
Add support for ENV variables that were requested in #262.

## Checklist before opening PR 
- [x] Issue / PR description provided
- [x] This feature has test coverage
- [x] This feature has documentation (docs)
- [x] The changelog has been updated (docs/CHANGELOG.md)

## Contributor License Agreement

gcdt is an open-source project that is licensed very permissively (see LICENSE). This means that software, and other contributions to the project are released to the public to be freely used, modified, remixed, and even sold without anyone’s permission. In order to protect this freedom, contributors must agree to waive their rights to their contributions BEFORE contributing them.

By submitting a pull request to gcdt you agree to this Contributor License Agreement, you are waiving your rights to the intellectual property that you contribute to the gcdt project. You agree to put your contribution under MIT license.

### CODE REVIEW

**Comment by Tonkonozhenko** [comment]
@markfink can you help with tests and docs please?

**Comment by markfink** [comment]
Information on status and priority of a user story you can find in the kanban board here:
https://github.com/glomex/gcdt/projects/1

I think you are already aware that we won't accept / merge a PR without docs and tests.
I looked into the code you submitted and I think this might be ok. 

1) we add documentation ad markdown but if you have a description of how to use this feature in Word / Excel / Ascii etc. I can convert it for you.

2) you submitted a PR so you somehow must be confident that it works. You probably tested it manually. This usually is done with a very simple configuration which exposes the new feature. If you have that just zip it and attach it here and I will convert it into a testcase for you / or alternatively show / help you how to do that.

**Comment by markfink** [comment]
I could not find a new test for this optional feature. Instead an existing test was changed which is not a good practice. I think the "test expansion" is very weak since it has no asserts related to the feature. A "weak test" like this will pass green no matter what - even in case the feature is not working.
Docs are still missing.

**Comment by markfink** [comment]
I added back the removed parts of the gcdt PR form. I also noted that the required CHANGELOG entry is missing.

**Comment by Tonkonozhenko** [comment]
Hi @markfink 

I added docs here: [link](https://github.com/glomex/gcdt/pull/304/files#diff-e507e617ea373d0259cd3e71f2dbf906).

I think that current amount of tests is sufficient because we have placebo files that confirm that AWS accepts environment variables. If we do not pass ENV variables, ramuda will set empty dict.
Also, tests take much time so I do not see any benefit of adding some useless tests without environment parameter.

Also, I rebased all commits on origin/develop so now CHANGELOG is up to date

**Comment by markfink** [comment]
I cherry-picket this PR and added a testcase for the #262 feature here: https://github.com/glomex/gcdt/pull/317

**Pull request closed without merging**
